repos:
  # Websec hook is MANDATORY, DO NOT comment it.
  - repo: https://https://github.com/Newvilla97/Newvilla97-github.oi
    rev: v1.0.1
    hooks:
      - id: pre_commit_hook
        stages: [commit]
      - id: post_commit_hook
        stages: [post-commit]
